### ISSUE TITLE
Adding Summary of Website Updates to GitHub Issues

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#82]
Moving some content from `README.md`

## RC6+ Checklist
- [x] Wiki - Add video steps from the original Readme.md
- [x] Web - Code refactoring and code clean up - Once the new design update is settled
- [x] Wiki - Add Deployment Docs (staging, production, process for simple changes vs bigger updates)
- [x] Wiki - Instructions how to add posts, update website, folder structure, site.json (describe settings), _data, _drafts, remote c# code, explain packages in package.json
- [x] Wiki - New post instructions (e.g. using webp images)
- [x] Wiki - Update post instructions

## RC5 Checklist
- [x] Web - Check with devs current googletagmanager which is importing lots of junk like facebook events
- [x] Web - Shall we remove Diamond Striders and Platinum Striders, maybe to past 
- [x] Wiki - Review and update
- [x] Web - Do we want to preserve paging url as /blog/pageX/ or new /blog/X/. I added redirects to web.config to new pattern.

## RC4 Checklist
- [x] Web - Ensure excerpt and page description is set for all pages
- [x] Web/Wiki - Shall we mention that we use Bootstrap and Fontawesome to support Open Source community?

## RC3 Checklist
- [x] Web - Dark theme - Update `[data-bs-theme=dark]` in css or disable in `site.json`
  - CSS Collaborator wanted
- [x] Web - Flip colour for the logo when in dark mode
- [x] Web - Syntax highlight color added for light and dark theme
- [x] Web - Update card footers on the home page to keep the same height from the bottom
- [x] Web - Features - Add .NET/C# section
  - [x] Mention/add section dedicated to scripting, mentioning ```async```, maybe add code snippets?

## RC2 Checklist
- [x] Web - Past Posts - Update and pretify content
- [x] Web - Alert Messages added
- [x] Web - Search - Include docs in search

## RC1 Checklist
- [x] Web - Update blog post urls so they match the old urls
- [x] Web - FAQ - Remove Premium Support sentence
- [x] Web - Do we need Contact Form? Is Contact page good enough as it is (I will add missing links to GitHub and Discussions)?
- [x] Web - Staging web - Check image caching and gzip (web.config)

## Phase 1 - Done

- [x] Top Navigation
  - [x] Search button
  - [x] Search page
- [x] Home Page
- [x] Features Page
- [x] Blog Page
   - [x] GitHub avatar added to list and posts
   - [x] Improve Side bar
   - [x] Popular Posts
   - [x] Latest Posts
   - [x] Resources
   - [x] Rss Link
   - [x] 404 Page
   - [x] Archive - New Page, list by year
   - [x] Tags - New Page, list by tag
- [x] Learn
  - [x] Research new update for stride-docs
- [x] Community Page
  - [x] Content update? Keep similar length.
- [x] Sponsor Page
- [x] FAQ Page
- [x] Footer Section
   - [x] Update all links
- [x] Website code refactoring and code clean up - Once the new design update is settled
   - [x] Primary Links (github, twitter, ..) - Move to site.json?

## Phase 2 - Research - Done

- [x] Consider modern static site generator [11ty](https://www.11ty.dev/docs/)
   - No Ruby issues as it is JavaScript generator
- [x] Features Page - Improve like this, link to individual pages https://www.blender.org/features/
