### ISSUE TITLE
Updated Website Release Checklist

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#94]
**ToDo Dependencies**

- [x] Double check that URLs match the old website, especially the critical/main pages 
   - Note that old website blog post pager links (/page2/, /page3/, etc.) are redirect to the new website /blog/x/ through web.config 
- [x] There are linked items from https://www.stride3d.net/ to https://doc.stride3d.net/ what can we do? If we can't redeploy old docs websites (3.0, 3.1, 4.0, 4.1) we have to add these old items to the new website, obviously, the new website won't be utilising them
   - //stride3d.net/css/site.css
   - //stride3d.net/scripts/site.doc.js
   - //stride3d.net/favicon.png - this remain on the new website
   - //stride3d.net/scripts/theme.js
- [x] Check the launcher - xen2: we display "getting started" and news in launcher right pane
  I think "getting started" comes from doc, but news come from our website, possibly some rss feed?

**ToDo Branches**
- [x] Conduct final tests on the `staging-next` branch.
- [x] Wait for the go-ahead from the team.
- [x]  @VaclavElias - Create a Pull Request (PR) to merge `staging-next` into `master`.
- [x]  @VaclavElias - Ensure `master` branch serves as our stable working branch (probably it does already).
- [x]  @VaclavElias - Create a PR to merge `master` into the `release` branch.
- [x] @xen2 - Create a new separate website for the release branch, it should be exactly the same as the staging but connected to the release branch. 
- [x] @VaclavElias - Configure CI/CD for the `release` branch to automatically trigger on push and pull events also allow manually to trigger
- [x] @VaclavElias -  Test the new website
- [x] @xen2 - Change A Record to point to the new website (we should keep the old website temporarily)
- [x] Test Live website
- [x] ~~@xen2 - Stop the old website - We can keep it for some time~~ We will keep it running
- [x] @VaclavElias -  Delete the existing `staging` branch, due to unrelated commit history.
- [x] @VaclavElias - Rename `staging-next` to `staging`.

**Comment by VaclavElias** [comment]
Regarding the RSS feed, the url path is the same but I used for some reason **Atom feed standard**, while the old website is using **RSS feed standard**. 

I think the main reason is that Atom feed supports author name for each article, and I wanted to give a credit also in the rss feed. The RSS feed standard supports email only (not name) for the article, which might not be convenient to provide. 

I think, let's stick with the old version for now, and I will create a ticket for grab to update the feed to Atom feed, with a dependency on the Stride launcher panel.

The new feed will remain there as well, but I will change the url path so it will be just sleeping there 🤣 and waiting for a resurrection.

**Comment by VaclavElias** [comment]
The launcher is working with the new website feed. The feed was updated to the original rss feed format.

<img width="768" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/815d9343-ad6e-4553-aab1-e9d70aabaad9">

**Comment by VaclavElias** [comment]
@xen2, I have DM you in Discord with some additional instructions.

I have created PS script, which updated the links and removed the dependency on the stride3d.net website.

These links were updated:

```
$replacements = @{
    '//stride3d.net/css/site.css' = '/css/site.css';
    '//xenko.com/css/site.css' = '/css/site.css';
    '//stride3d.net/scripts/site.doc.js' = '/scripts/site.doc.js';
    '//xenko.com/scripts/site.doc.js' = '/scripts/site.doc.js';
    '//stride3d.net/favicon.png' = '/favicon.png';
    '//xenko.com/favicon.png' = '/favicon.png';
    '//stride3d.net/scripts/theme.js' = '/scripts/theme.js';
    '//xenko.com/scripts/theme.js' = '/scripts/theme.js';
}
```

Test Stride Docs website here https://stride-docs-test.azurewebsites.net/latest/en/

If all ok, I will upload the 4 zip files, which you can unzip through Azure App Service Kudu.

We will keep the old versions temporarily (version-old folder)

![image](https://github.com/stride3d/stride-website/assets/4528464/56d27fb7-565c-43a6-b29b-6ad8eaf68c6a)

**Comment by VaclavElias** [comment]
@xen2, the Stride Docs updates are now live. 

- The dependency on the stride3d.net website was removed. 
- The cache is funny so it might take some time to see it in your browser. 
- The original docs folders were renamed to **-old**, so we have got a backup in case we need to reverse. It is easy to rename the folders through FTP or App Service Editor

<img width="383" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/cee8f405-cdc3-4e67-92e3-8a9e2d880d13">
<img width="164" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/c7014545-dce4-4b34-b03e-86d6c418c6ac">

If it is ok with you I can continue with the steps described above.

**Comment by VaclavElias** [comment]
This is now all done. Closing.
