### ISSUE TITLE
After Release Checklist

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#97]
- [x] Test the website
- [x] Test the launcher
- [x] Test installer download

**Comment by VaclavElias** [comment]
The Stride Launcher is loading the news from the new website. 

<img width="299" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/c33374c6-7ab8-42d1-9e04-d5277fd4a3dc">

All other bits were tested. Closing this issue.
